# Generated by Django 4.2.7 on 2023-11-04 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hospital", "0003_alter_patient_doctor_alter_patient_gender_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vitals",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("platelet", models.IntegerField()),
                ("Hba", models.DecimalField(decimal_places=2, max_digits=5)),
                ("potassium", models.DecimalField(decimal_places=2, max_digits=5)),
                ("sodium", models.DecimalField(decimal_places=2, max_digits=5)),
                ("dDimer", models.DecimalField(decimal_places=2, max_digits=5)),
                ("sgot", models.DecimalField(decimal_places=2, max_digits=5)),
                ("sgpt", models.DecimalField(decimal_places=2, max_digits=5)),
                ("tlc", models.DecimalField(decimal_places=2, max_digits=5)),
                ("ph", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hospital.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Checkup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("comment", models.TextField()),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hospital.doctor",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hospital.patient",
                    ),
                ),
                (
                    "vital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="checkup.vitals"
                    ),
                ),
            ],
        ),
    ]
