# Generated by Django 4.1 on 2023-11-04 20:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("staffs", models.IntegerField(default=0)),
                ("patients", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("doa", models.DateTimeField(auto_now_add=True)),
                ("dos", models.DateTimeField(blank=True, default=None, null=True)),
                ("phonenumber", models.CharField(max_length=100)),
                ("gender", models.CharField(max_length=100)),
                ("ward", models.CharField(max_length=100)),
                ("sr", models.CharField(max_length=100)),
                (
                    "diagnosis_detail",
                    models.TextField(blank=True, default=None, null=True),
                ),
                ("dob", models.DateTimeField(blank=True, default=None, null=True)),
                ("age", models.IntegerField(default=0)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hospital.doctor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="RFID",
            fields=[
                (
                    "rfid",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "pid",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hospital.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("report", models.FileField(upload_to="media/reports")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hospital.patient",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hospital.staff"
                    ),
                ),
            ],
        ),
    ]
