# Generated by Django 4.1 on 2023-11-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient", name="doctor", field=models.CharField(max_length=100),
        ),
    ]
