# Generated by Django 4.2.7 on 2023-11-04 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0002_alter_patient_doctor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="doctor",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="gender",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="phonenumber",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="sr",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="ward",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
