# Generated by Django 4.2.7 on 2023-11-05 01:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0003_alter_patient_doctor_alter_patient_gender_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rfid",
            name="time",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime.now, null=True
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="uid",
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
